server:
  port: 8089
spring:
#  config:
#    activate:
#      on-profile: local # dev라고 이름을 지정하는 것이다.
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordersystem
    username: root
    password: 1234

#  # rabbit mq 환경 설정
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: / # 관례적으로 적는 것


  jpa:
    database : mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
logging:
  level:
    root: info
    # 로그 레벨: trace < debug < info < error 순서의 로그 레벨을 가진다.
    # 즉, info로 설정시 trace, debug 로그는 출력되지 않음
    # 로그 파일 경로와 파일 명 지정
  file:
    name: logs/app.log

jwt:
  expiration: 30
  secretKey: my_token_secret
  expiration-rt: 14400 # 10일
  secretKey-rt: hackathon

cloud:
  aws:
    credentials:
      access-key: xxx
      secret-key: yyy
    region:
      static: ap-southeast-2
    s3:
      bucket: woojin-bucket




